# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed6e6290c6614f1febfae23847e0f128275c8025ddd0ef447534a1fe9b927b9f499622ed250d30f6baf27b719af79c1701766f1fe57a8e8394909d9ee034e91b

test:
  secret_key_base: d07ecaba10fef3abd0c30713d9c5f3d93b0843c39c5b417cb0a8d7c92067d87724165079bcc72901fe84b93bd1dcd99a4ddfe284f13b8dba38a822ba44e87398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
